#!/bin/bash

build_num=`cat build_num.txt`
newnum=`expr $build_num + 1`
echo $newnum >  build_num.txt

export build_num=$newnum

curl -L https://yt-dl.org/downloads/latest/youtube-dl -o youtube-dl


docker build -t rc3labs/youtube-dl . \
 --label "build=${build_num}" \
 --label "version=1.0" \
 --label "maintainer"="harvey.cary@rc3labs.com" \
 --label "author"="Harvey Cary (hcary@rc3labs.com)" \
 --label "company"="rc3labs.com" 

rm youtube-dl