#!/bin/bash

MYUSER=$USER
MYUID=`id -u $USER`
DEST=/home/$MYUSER


sudo docker run \
    --rm \
    --name $USER.$$ \
    -e "MYUSER=$MYUSER" \
    -e "MYUID=$MYUID" \
    -t \
    -i \
    --mount 'type=bind,src='$HOME',dst=/home/hcary' \
    rc3labs/youtube-dl \
    /bin/bash

